In [6]:
import os
import sys

folder = "../"
project_root = os.path.abspath(os.path.join(os.path.dirname('__file__'), '..'))
sys.path.append(project_root)

In [7]:
from utils.data_generation import generate_dataset_random

In [18]:
cartesion = generate_dataset_random(
    batch_size=1024, n_batches=10
)[0]

print(cartesion.numpy())


import plotly.graph_objects as go

# Create the 3D scatter plot
fig = go.Figure(data=[go.Scatter3d(
    x=cartesion[:,0],
    y=cartesion[:,1], 
    z=cartesion[:,2],
    mode='markers',
    marker=dict(
        size=2,
        color=cartesion[:,2],  # Color points by z-coordinate
        colorscale='Viridis',
        opacity=0.8
    )
)])

# Update layout for better visualization
fig.update_layout(
    title='Equidistant Points on Unit Sphere',
    scene=dict(
        xaxis=dict(showgrid=False, zeroline=False, showline=False, showticklabels=False, showbackground=False, title=''),
        yaxis=dict(showgrid=False, zeroline=False, showline=False, showticklabels=False, showbackground=False, title=''),
        zaxis=dict(showgrid=False, zeroline=False, showline=False, showticklabels=False, showbackground=False, title=''),
        bgcolor='black'
    ),
    width=800,
    height=800
)

# Show the interactive plot
fig.show()



[[-0.5651721   0.1348302   0.59646004]
 [ 0.5252559  -0.6162915  -0.48928154]
 [ 0.9327421   0.20801102  0.02465766]
 ...
 [ 0.08009924  0.14322169  0.9839283 ]
 [ 0.27829093 -0.5630964   0.6267943 ]
 [-0.43718743  0.33884168 -0.34497982]]


ValueError: 
    Invalid value of type 'tinygrad.tensor.Tensor' received for the 'color' property of scatter3d.marker
        Received value: <Tensor <UOp METAL (10240,) float ShapeTracker(views=(View(shape=(10240,), strides=(3,), offset=2, mask=None, contiguous=False),))> on METAL with grad None>

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color:
            aliceblue, antiquewhite, aqua, aquamarine, azure,
            beige, bisque, black, blanchedalmond, blue,
            blueviolet, brown, burlywood, cadetblue,
            chartreuse, chocolate, coral, cornflowerblue,
            cornsilk, crimson, cyan, darkblue, darkcyan,
            darkgoldenrod, darkgray, darkgrey, darkgreen,
            darkkhaki, darkmagenta, darkolivegreen, darkorange,
            darkorchid, darkred, darksalmon, darkseagreen,
            darkslateblue, darkslategray, darkslategrey,
            darkturquoise, darkviolet, deeppink, deepskyblue,
            dimgray, dimgrey, dodgerblue, firebrick,
            floralwhite, forestgreen, fuchsia, gainsboro,
            ghostwhite, gold, goldenrod, gray, grey, green,
            greenyellow, honeydew, hotpink, indianred, indigo,
            ivory, khaki, lavender, lavenderblush, lawngreen,
            lemonchiffon, lightblue, lightcoral, lightcyan,
            lightgoldenrodyellow, lightgray, lightgrey,
            lightgreen, lightpink, lightsalmon, lightseagreen,
            lightskyblue, lightslategray, lightslategrey,
            lightsteelblue, lightyellow, lime, limegreen,
            linen, magenta, maroon, mediumaquamarine,
            mediumblue, mediumorchid, mediumpurple,
            mediumseagreen, mediumslateblue, mediumspringgreen,
            mediumturquoise, mediumvioletred, midnightblue,
            mintcream, mistyrose, moccasin, navajowhite, navy,
            oldlace, olive, olivedrab, orange, orangered,
            orchid, palegoldenrod, palegreen, paleturquoise,
            palevioletred, papayawhip, peachpuff, peru, pink,
            plum, powderblue, purple, red, rosybrown,
            royalblue, rebeccapurple, saddlebrown, salmon,
            sandybrown, seagreen, seashell, sienna, silver,
            skyblue, slateblue, slategray, slategrey, snow,
            springgreen, steelblue, tan, teal, thistle, tomato,
            turquoise, violet, wheat, white, whitesmoke,
            yellow, yellowgreen
      - A number that will be interpreted as a color
        according to scatter3d.marker.colorscale
      - A list or array of any of the above